const Images = {
  amal_image: require("./amal-photo.jpg"),
  amal_image_2: require("./amal-photo-2.jpg"),
  twitter_icon: require("./twitter.png"),
  facebook_icon: require("./facebook.png"),
  linkedin_icon: require("./linkedin.png"),
  instagram_icon: require("./instagram.png"),
  painting: require("./painting.jpg"),
  painting_1: require("./painting-1-1.jpg"),
  painting_2: require("./painting-2.jpeg"),
  painting_3: require("./painting-3.jpeg"),
  painting_4: require("./painting-4.jpeg"),
  painting_5: require("./painting-5.jpeg"),
  baghdad: require("./bg-7.jpg"),
  baghdad_2: require("./image-of-baghdad.jpg"),
  teaching: require("./teaching.jpg"),
  teaching_2: require("./teaching-2.jpg"),
  food: require("./food.jpg"),
  net_cafe: require("./net-cafe.jpg"),
  surgeon: require("./surgeon.jpg"),
  logo: require("./logo.png"),
  video: require("./file.mp4"),
  amals_banner: require("./amals-banner.jpg"),
  baghdad_15: require("./baghdad-15.jpg"),
  baghdad_12: require("./baghdad-12.jpg"),
  baghdad_9: require("./baghdad-9.jpg"),
  baghdad_8: require("./baghdad-8.jpg"),
  baghdad_13: require("./baghdad-13.jpg"),
  baghdad_16: require("./baghdad-16.jpg"),
  baghdad_17: require("./baghdad-17.jpeg"),
  baghdad_18: require("./baghdad-18.jpg"),
  anbar: require("./anbar.jpg"),
  anbar_2: require("./anbar-2.jpg"),
  iraq_map: require("./iraq-map.png"),
  header_bg: require("./header-bg-1.jpg"),
  desert: require("./desert-mask.png"),
  baghdad_birds: require("./baghdad-birds.jpg"),
  baghdad_19: require("./baghdad-19.jpg"),
  baghdad_20: require("./baghdad-20.jpg"),
  moon: require("./moon.png"),
  painting_knights: require("./painting-knights.jpg"),
  night_sky: require("./night-sky.jpg"),
  flowers: require("./flowers.gif"),
  bridge_2: require("./bridge-2.jpg"),
};

export default Images;
