const Images = {
  amal_image: require("./amal-photo.jpg"),
  amal_image_2: require("./amal-photo-2.jpg"),
  twitter_icon: require("./twitter.png"),
  facebook_icon: require("./facebook.png"),
  linkedin_icon: require("./linkedin.png"),
  instagram_icon: require("./instagram.png"),
  painting: require("./painting.jpg"),
  painting_1: require("./painting-1-1.jpg"),
  painting_2: require("./painting-2.jpeg"),
  painting_3: require("./painting-3.jpeg"),
  painting_4: require("./painting-4.jpeg"),
  painting_5: require("./painting-5.jpeg"),
  baghdad: require("./bg-7.jpg"),
  baghdad_2: require("./image-of-baghdad.jpg"),
  teaching: require("./teaching.jpg"),
  teaching_2: require("./teaching-2.jpg"),
  food: require("./food.jpg"),
  net_cafe: require("./net-cafe.jpg"),
  surgeon: require("./surgeon.jpg"),
  logo: require("./logo.png"),
  video: require("./file.mp4"),
  amals_banner: require("./amals-banner.jpg"),
};

export default Images;
